name: timeflux-ssvep
channels:
  - conda-forge
  - defaults
dependencies:
- python>=3.7
- networkx>=2.4
- pyyaml>=5.1
- numpy>=1.17
- pandas>=0.25
- xarray>=0.14
- bottleneck>=1.3
- scipy>=1.3
- pyzmq>=18.1
- coloredlogs>=10.0
- pytables>=3.6
- jsonschema>=3.0
- python-dotenv>=0.10
- pytest>=5.3
- sphinx>=2.2
- sphinx_rtd_theme>=0.4
- python-graphviz>=0.13
- pip>=19.3
- matplotlib # Needed, since this package is missing in pyriemann setup dependencies
- pip:
  - pyriemann
#  - pylsl>=1.13.1c
  - git+https://github.com/timeflux/timeflux@04706f5#egg=timeflux
  - git+https://github.com/timeflux/timeflux_dsp
  - git+https://github.com/timeflux/timeflux_ui
  - git+https://github.com/timeflux/timeflux_ui
  - git+https://github.com/timeflux/timeflux_openbci